In [10]:
import nltk
import re
import pandas as pd

In [11]:
data = pd.read_excel('error_dataset12.xlsx')

In [12]:
data

,Unnamed: 0,Unnamed: 0.1,Comments,M_Class
0,0,0,wonderful የተግባር ሆናቿል የwifi መቆራረጧንና ፍጥነት መቀነሷን ...,positive
1,1,1,telebirr ስከፍት የተሰጠኝን bonus እንዴት መጠቀም እችላለው,positive
2,2,2,ከባንክ ወደቴሌ ገንዘብ ስታስተላልፍ ቦነስ አለው ደስ ይላል አይደል በነገ...,positive
3,3,3,internet speed አስተካክሉ በጣም አይፈጥንም የብዙዎች ጥያቄ,positive
4,4,4,በሲዳማ ክልል ከሀዋሳ ዉጭ በቱም ወረዳ የሞባይል data connection...,negative
...,...,...,...,...
1746,1746,1746,well done,positive
1747,1747,1747,ethio tele good change,positive
1748,1748,1748,too expensive,negative
1749,1749,1749,a good improvment bravo,positive
1750,1750,1750,okay thanks,positive

In [13]:
#stopword list uploading
stopwords = pd.read_excel('stopwords.xlsx', header=None)
stopwords = stopwords[0].to_list()

#applying stopword removal on dataset
data['Comments'] =data['Comments'].apply(lambda x: ' '.join([word for word in x.split() 
                                                             if word not in (stopwords)]))

In [14]:
stopwords = stopwords[0].to_list()

In [15]:
data['Comments'] = data['Comments'].astype('str')

In [16]:
data['Comments'] =data['Comments'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stopwords)]))

In [17]:
data

,Unnamed: 0,Unnamed: 0.1,Comments,M_Class
0,0,0,wonderful የተግባር ሆናቿል የwifi መቆራረጧንና ፍጥነት መቀነሷን ...,positive
1,1,1,telebirr ስከፍት የተሰጠኝን bonus እንዴት መጠቀም እችላለው,positive
2,2,2,ከባንክ ወደቴሌ ገንዘብ ስታስተላልፍ ቦነስ አለው ደስ ይላል አይደል በነገ...,positive
3,3,3,internet speed አስተካክሉ በጣም አይፈጥንም የብዙዎች ጥያቄ,positive
4,4,4,በሲዳማ ክልል ከሀዋሳ ዉጭ በቱም ወረዳ የሞባይል data connection...,negative
...,...,...,...,...
1746,1746,1746,well done,positive
1747,1747,1747,ethio tele good change,positive
1748,1748,1748,too expensive,negative
1749,1749,1749,good improvment bravo,positive
1750,1750,1750,okay thanks,positive

In [1]:
writer = pd.ExcelWriter('error_dataset123.xlsx', engine='xlsxwriter')
data.to_excel(writer, sheet_name='data')
writer.save()

NameError: name 'pd' is not defined